# Generated by Django 3.2.4 on 2021-06-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provide_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.CharField(blank=True, max_length=100, null=True)),
                ('company_location', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_requirement', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('demand_num', models.CharField(blank=True, max_length=100, null=True)),
                ('job_requirements', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
